php bin/console VMouvementDebitCaisseSiege
php bin/console VMouvementDebitBanque
php bin/console VMouvementCreditCaisse
php bin/console VMouvementCreditBanque
php bin/console VDebitCaisseMensuel
php bin/console VDebitBanqueMensuel